# Generated by Django 2.2 on 2020-05-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
