# Generated by Django 2.2 on 2020-06-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200524_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zomato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant', models.CharField(max_length=250)),
                ('City', models.CharField(max_length=250)),
                ('Cuisines', models.CharField(max_length=250)),
                ('cost', models.IntegerField(null=True)),
                ('tablebook', models.CharField(max_length=250)),
                ('onlinedelivery', models.CharField(max_length=250)),
                ('rating', models.IntegerField(null=True)),
                ('Votes', models.IntegerField(null=True)),
            ],
        ),
    ]
