# Generated by Django 2.2 on 2020-06-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_zomato'),
    ]

    operations = [
        migrations.CreateModel(
            name='zoamto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant', models.CharField(max_length=250)),
                ('PRICE', models.CharField(max_length=250)),
                ('CUISINECATEGORY', models.CharField(max_length=250)),
                ('CITY', models.CharField(max_length=250)),
                ('CUISINETYPE', models.CharField(max_length=250)),
                ('STARTTIME', models.CharField(max_length=250)),
                ('EndTime', models.CharField(max_length=250)),
                ('RATING', models.CharField(max_length=250)),
                ('RATING_TYPE', models.CharField(max_length=250)),
            ],
        ),
    ]
