# Generated by Django 2.2 on 2020-06-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_zoamto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoamto',
            name='EndTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='zoamto',
            name='PRICE',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='zoamto',
            name='RATING',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='zoamto',
            name='STARTTIME',
            field=models.TimeField(null=True),
        ),
    ]
