# Generated by Django 2.2 on 2020-06-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_zoamto_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoamto',
            name='EndTime',
        ),
        migrations.RemoveField(
            model_name='zoamto',
            name='STARTTIME',
        ),
    ]
