# Generated by Django 2.2 on 2020-06-18 14:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adddetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('explanation', models.TextField(max_length=2000)),
                ('date', models.DateField(default=datetime.datetime(2020, 6, 18, 19, 54, 25, 686715))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.Addemp')),
            ],
        ),
    ]
